### ISSUE TITLE
Release v0.4

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/trackpy#441]
We are heading for a big release, containing:

- Refactor of locate to make it more modular. Some API breaks. (PR 400, 406
- Better performance of gray dilation (PR 361)
- Fix compute drift if dataframes are not sorted (PR 409)
- New refinement using least squares optimization (PR 407)
- New linker that combines gray dilation and linking `FindLinker` (PR 407, 410, 411, 416, 428)
- Refactor of the linking code to give the `Linker` and `FindLinker` a common code base and better API (PR 416)
- Fix double counting of non-linking penalty in non-numba linkers (PR 430)
- Fix the `N` column for `emsd` (PR 434)

On the milestone list are the following:

- [x] Make `locate` even more modular #257
- [x] Adjust default value of `smoothing_size` to the Crocker Grier value #401
- [x] Finish the refactor of the linking code, breaking a part of the linking API (building on #416)
- [ ] Supply a parallelized `batch` function #304 
- [ ] Investigate skimage's moment computations #265 
- [ ] Investigate normalization questions raised in #239
- [ ] Read/write OpenPTV files #243 

I think we should finish the refactor of the linking code, better to change the API in one release. But for the rest, we could postpone until a later release. Thoughts? @danielballan @nkeim @tacaswell

**Comment by nkeim** [comment]
I agree with this plan! Finishing the linking refactor is enough work all by itself, because we also should check performance (asv) and that the output does not change. In principle the benchmarking code just needs to be dusted off and run, but it's been a long time.

I must say trackpy v0.3 has had amazing longevity; my group is still using it as released. Exactly what you want in scientific software!

On Jun 9, 2017, 1:04 PM -0700, Casper van der Wel <notifications@github.com>, wrote:

We are heading for a big release, containing:

  *   Refactor of locate to make it more modular. Some API breaks. (PR 400, 406
  *   Better performance of gray dilation (PR 361)
  *   Fix compute drift if dataframes are not sorted (PR 409)
  *   New refinement using least squares optimization (PR 407)
  *   New linker that combines gray dilation and linking FindLinker (PR 407, 410, 411, 416, 428)
  *   Refactor of the linking code to give the Linker and FindLinker a common code base and better API (PR 416)
  *   Fix double counting of non-linking penalty in non-numba linkers (PR 430)
  *   Fix the N column for emsd (PR 434)

On the milestone list are the following:

  *    Make locate even more modular #257<https://github.com/soft-matter/trackpy/issues/257>
  *    Adjust default value of smoothing_size to the Crocker Grier value #401<https://github.com/soft-matter/trackpy/issues/401>
  *    Finish the refactor of the linking code, breaking a part of the linking API (building on #416<https://github.com/soft-matter/trackpy/pull/416>)
  *    Supply a parallelized batch function #304<https://github.com/soft-matter/trackpy/issues/304>
  *    Investigate skimage's moment computations #265<https://github.com/soft-matter/trackpy/issues/265>
  *    Investigate normalization questions raised in #239<https://github.com/soft-matter/trackpy/pull/239>
  *    Read/write OpenPTV files #243<https://github.com/soft-matter/trackpy/issues/243>

I think we should finish the refactor of the linking code, better to change the API in one release. But for the rest, we could postpone until a later release. Thoughts? @danielballan<https://github.com/danielballan> @nkeim<https://github.com/nkeim> @tacaswell<https://github.com/tacaswell>

**Comment by danielballan** [comment]
I think that's a good plan. The rest of the API changes deserve very careful attention which I think none of us now have much to give it at this moment.

I was just at Penn for a friend's defense (Paulo was on the committee, @nkeim) and was trying to roust up another grad student contributor to take on this kind of thing.

**Comment by nkeim** [comment]
Linking to the [Release Checklist](https://github.com/soft-matter/trackpy/wiki/Release-Checklist) for reference. If this isn't out by December I could take the lead.

**Comment by charlesreid1** [comment]
I'm happy to continue with my own modest contributions as well! Although most of the release checklist contains things for core contributors, please let me know if there's anything that might need some attention before the release.

**Comment by nkeim** [comment]
@charlesreid1 Thanks! Your help is always welcome and I promise the rest of us will try to keep up. That is how we all got involved! (Well, except for @tacaswell and @danielballan :).

**Comment by Resonanz** [comment]
Any updates on ver 0.4 ?

**Comment by caspervdw** [comment]
@Resonanz it is waiting for the investigation of #472

**Comment by caspervdw** [comment]
Thanks to @nkeim for the last fix, trackpy is ready for the next major release! Any objections? @danielballan  @tacaswell

**Comment by nkeim** [comment]
Great! I am only part done with #452 but maybe it is not worth holding up the release for that. It is only another ~1 hour of focused work, but I can't promise I can finish it in the next ~3 weeks.

**Comment by Resonanz** [comment]
Thanks heaps guys, I will test the walkthrough on a fresh install this week hopefully.

**Comment by nkeim** [comment]
@caspervdw is moving fast 🚀! Just a heads up: I will be offline from Sunday-ish through Wednesday.

**Comment by caspervdw** [comment]
I will do the release tomorrow if there are no further objections.

**Comment by nkeim** [comment]
Great! I've run the master branch on another massive data set and it seems to do fine this time. I have created #484 to make the release notes more helpful; please have a look.

**Comment by caspervdw** [comment]
Thanks @nkeim, I merged them and then did the release. All done: the release is visible on PyPI and Zenodo, and the docs are updated as well.

Only waiting for https://github.com/conda-forge/trackpy-feedstock/pull/7 before the conda release.

Tagging @sciunto in case he has time to do the Arch packaging.

**Comment by apiszcz** [comment]
This is looking close, any idea when it it will appear in Conda. I may be brave enough to test.

**Comment by caspervdw** [comment]
Probably tomorrow! @apiszcz

**Comment by Resonanz** [comment]
I hope to have time tomorrow to test via Conda 😀




Get Outlook for Android







On Fri, Apr 6, 2018 at 8:15 AM +1200, "Casper van der Wel" <notifications@github.com> wrote:












Probably tomorrow! @apiszcz

**Comment by Resonanz** [comment]
If i Get the time, i will install on Debian and Windows10 using python3.6 (or3.5)..... Is that a good idea or would you prefer another python version?




Get Outlook for Android







On Fri, Apr 6, 2018 at 8:34 AM +1200, "Rob Ward" <rob.ward.nz@gmail.com> wrote:










I hope to have time tomorrow to test via Conda 😀




Get Outlook for Android







On Fri, Apr 6, 2018 at 8:15 AM +1200, "Casper van der Wel" <notifications@github.com> wrote:












Probably tomorrow! @apiszcz

**Comment by sciunto** [comment]
packages are updated for archlinux. 

Many thanks for your work on this library :)

**Comment by caspervdw** [comment]
Thanks @sciunto !

@nkeim Yes thats right, as soon as all builds pass you can hit merge, then the packages get uploaded to anaconda.org. I just did and the OS X and Linux builds are up already.

For the next time: there apparently is a bot that keeps track of PyPI (I think) and automatically creates the PR at conda-forge. So there was no need to do that myself. (It does not bump dependencies, however!)

**Comment by caspervdw** [comment]
@sciunto  We did another release; v0.4.1 does not depend om pims anymore, simplifying installation. Could you have a look at the arch packages again?
